version: "3"
services:
  petBridge:
    image: petbridge:0.0.1
    container_name: pet-bridge
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: "8gb"
    runtime: nvidia
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./ext-drive:/ext-drive
    working_dir: /encoder4editing
    network_mode: "host"
    tty: true
    restart: always
